name: Build and Push Spring Boot Project Image to Google Cloud Platform
on:
  push:
    branches: [ "master" ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE: google-kubernetes-image
      PROJECT_ID: my-kubernetes-project-392907
      GAR_LOCATION: asia-south1
      REPOSITORY: google-kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: 'Docker build'
        run: docker build . --file Dockerfile --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - name: Push Docker Image to GAR
        uses: par-tec/docker-push-gar-image@v0.0.3
        with:
          image_name: ${{ env.REPOSITORY }}/${{ env.IMAGE }}
          image_tag: ${{ github.sha }}
          gar_hostname: asia-south1-docker.pkg.dev
          gar_project: ${{ env.PROJECT_ID }}
          gar_service_account: ${{ secrets.SERVICE_ACCOUNT_KEY }}
